const SYSTEM_CONFIG={version:'1.0.0',officiallyApproved:false,rulesVersion:'1.0',testMode:false};const CONSENT_STORAGE_KEY='lyceum2_consent',MAINTENANCE_STORAGE_KEY='lyceum2_maintenance';const PUBLIC_PAGES=['','index.html','consent.html','login.html','maintenance.html'];const PAGE_ROLES={'admin.html':['admin'],'teacher.html':['teacher','admin'],'student.html':['student','admin'],'parent.html':['parent','admin']};
function getCurrentPage(){const p=location.pathname;return p.substring(p.lastIndexOf('/')+1)||'index.html'}
async function getCurrentUser(){if(typeof supabaseClient==='undefined'||!supabaseClient?.auth)return null;try{const {data}=await supabaseClient.auth.getUser();return data?.user||null}catch(e){console.error('Auth error:',e);return null}}
async function getCurrentProfile(){const u=await getCurrentUser();if(!u)return null;try{const {data,error}=await supabaseClient.from('profiles').select('id,email,full_name,role').eq('id',u.id).single();if(error)return null;return data}catch(e){console.error('Profile error:',e);return null}}
async function isLoggedIn(){return !!(await getCurrentUser())}
function getConsent(){try{return JSON.parse(localStorage.getItem(CONSENT_STORAGE_KEY))}catch{return null}}
function hasValidConsent(){const c=getConsent();return !!(c?.accepted&&c.version===SYSTEM_CONFIG.rulesVersion)}
function saveConsent(type='all'){localStorage.setItem(CONSENT_STORAGE_KEY,JSON.stringify({accepted:true,type,version:SYSTEM_CONFIG.rulesVersion,acceptedAt:new Date().toISOString()}))}
async function logout(){try{if(typeof supabaseClient!=='undefined'&&supabaseClient?.auth)await supabaseClient.auth.signOut()}catch(e){console.error('Logout error:',e)}localStorage.removeItem('lyceum2_user');location.href='login.html'}
function getMaintenanceState(){try{return JSON.parse(localStorage.getItem(MAINTENANCE_STORAGE_KEY))}catch{return null}}
function isMaintenanceEnabled(){return !!getMaintenanceState()?.enabled}
function setMaintenanceState(enabled,reason='',endTime=''){localStorage.setItem(MAINTENANCE_STORAGE_KEY,JSON.stringify({enabled,reason,endTime,updatedAt:new Date().toISOString()}))}
async function checkMaintenance(){if(!isMaintenanceEnabled())return false;const page=getCurrentPage();if(page==='maintenance.html')return true;const p=await getCurrentProfile();if(p?.role==='admin'||PUBLIC_PAGES.includes(page))return false;if(!PUBLIC_PAGES.includes(page)){location.href='maintenance.html';return true}return false}
async function checkAuthentication(){const page=getCurrentPage();if(PUBLIC_PAGES.includes(page))return true;if(!(await isLoggedIn())){location.href='login.html';return false}return true}
async function checkRoleAccess(){const page=getCurrentPage();if(!PAGE_ROLES[page])return true;const p=await getCurrentProfile();if(!p){location.href='login.html';return false}if(!PAGE_ROLES[page].includes(p.role)){location.href=({admin:'admin.html',teacher:'teacher.html',student:'student.html',parent:'parent.html'}[p.role]||'dashboard.html');return false}return true}
function toggleMenu(){document.querySelectorAll('.navigation,.main-nav').forEach(n=>n.classList.toggle('mobile-open'))}
function setupMobileMenu(){document.querySelectorAll('.mobile-menu,.mobile-menu-btn').forEach(b=>b.addEventListener('click',toggleMenu))}
function updateYear(){document.querySelectorAll('[data-year],#currentYear').forEach(e=>e.textContent=new Date().getFullYear())}
function setupLogoutButtons(){document.querySelectorAll('[data-logout],.logout-button,#logoutButton,#logoutBtn').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();logout()}))}
function setupScrollAnimations(){document.querySelectorAll('.feature-card,.stat-card,.card,.card-panel,.section').forEach(e=>e.classList.add('visible'))}
function updateSystemStatus(){document.querySelectorAll('[data-system-status]').forEach(e=>e.textContent=SYSTEM_CONFIG.officiallyApproved?'Офіційно підтверджено':'У розробці')}
function setupConsentButtons(){[['acceptAllRules','all'],['acceptRequiredRules','required'],['acceptCustomRules','custom']].forEach(([id,type])=>{const b=document.getElementById(id);if(b)b.addEventListener('click',()=>{saveConsent(type);location.href='login.html'})})}
async function updateUserElements(){const p=await getCurrentProfile();document.querySelectorAll('[data-user-name]').forEach(e=>e.textContent=p?.full_name||p?.email||'Користувач');document.querySelectorAll('[data-user-email]').forEach(e=>e.textContent=p?.email||'');document.querySelectorAll('[data-user-role]').forEach(e=>e.textContent={admin:'Адміністратор',teacher:'Вчитель',student:'Учень',parent:'Батьки'}[p?.role]||'Користувач')}
async function initializeApp(){setupMobileMenu();setupLogoutButtons();setupConsentButtons();updateYear();updateSystemStatus();setupScrollAnimations();const page=getCurrentPage();if(page!=='login.html')await checkMaintenance();if(!await checkAuthentication())return;if(!await checkRoleAccess())return;await updateUserElements()}
document.addEventListener('DOMContentLoaded',initializeApp);
